# Generated by Django 4.1.3 on 2023-08-23 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BidhaaZetu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ProductName', models.CharField(max_length=500)),
                ('ProductDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('ProductImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('status', models.CharField(blank=True, default='Bidhaa Zetu', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'BidhaaZetu',
            },
        ),
        migrations.CreateModel(
            name='Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day one', max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Days',
            },
        ),
        migrations.CreateModel(
            name='ElimuYaLishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Category', models.CharField(max_length=500)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'ElimuYaLishe',
            },
        ),
        migrations.CreateModel(
            name='Lishe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ItemName', models.CharField(max_length=500)),
                ('ItemDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('status', models.CharField(blank=True, default='LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Lishe',
            },
        ),
        migrations.CreateModel(
            name='MakundiYaChakula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FoodCategory', models.CharField(default='WANGA', max_length=500)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('Image', models.ImageField(blank=True, null=True, upload_to='media/MakundiYaChakulaImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'MakundiYaChakula',
            },
        ),
        migrations.CreateModel(
            name='PosterNaPicha',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Image', models.ImageField(upload_to='media/PosterNaPichaImages/')),
                ('status', models.CharField(blank=True, default='ELIMU YA LISHE', max_length=500, null=True)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'PosterNaPicha',
            },
        ),
        migrations.CreateModel(
            name='Weeks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 1', max_length=500)),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Weeks',
            },
        ),
        migrations.CreateModel(
            name='Week9',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 9', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week9',
            },
        ),
        migrations.CreateModel(
            name='Week8',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 8', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week8',
            },
        ),
        migrations.CreateModel(
            name='Week7',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 7', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week7',
            },
        ),
        migrations.CreateModel(
            name='Week6',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 6', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week6',
            },
        ),
        migrations.CreateModel(
            name='Week5',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 5', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week5',
            },
        ),
        migrations.CreateModel(
            name='Week45',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 45', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week45',
            },
        ),
        migrations.CreateModel(
            name='Week44',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 44', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week44',
            },
        ),
        migrations.CreateModel(
            name='Week43',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 43', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week43',
            },
        ),
        migrations.CreateModel(
            name='Week42',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 42', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week42',
            },
        ),
        migrations.CreateModel(
            name='Week41',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 41', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week41',
            },
        ),
        migrations.CreateModel(
            name='Week40',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 40', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week40',
            },
        ),
        migrations.CreateModel(
            name='Week4',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 4', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week4',
            },
        ),
        migrations.CreateModel(
            name='Week39',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 39', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week39',
            },
        ),
        migrations.CreateModel(
            name='Week38',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 38', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week38',
            },
        ),
        migrations.CreateModel(
            name='Week37',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 37', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week37',
            },
        ),
        migrations.CreateModel(
            name='Week36',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 36', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week36',
            },
        ),
        migrations.CreateModel(
            name='Week35',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 35', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week35',
            },
        ),
        migrations.CreateModel(
            name='Week34',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 34', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week34',
            },
        ),
        migrations.CreateModel(
            name='Week33',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 33', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week33',
            },
        ),
        migrations.CreateModel(
            name='Week32',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 32', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week32',
            },
        ),
        migrations.CreateModel(
            name='Week31',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 31', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week31',
            },
        ),
        migrations.CreateModel(
            name='Week30',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 30', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week30',
            },
        ),
        migrations.CreateModel(
            name='Week3',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 3', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week3',
            },
        ),
        migrations.CreateModel(
            name='Week29',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 29', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week29',
            },
        ),
        migrations.CreateModel(
            name='Week28',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 28', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week28',
            },
        ),
        migrations.CreateModel(
            name='Week27',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 27', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week27',
            },
        ),
        migrations.CreateModel(
            name='Week26',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 26', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week26',
            },
        ),
        migrations.CreateModel(
            name='Week25',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 25', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week25',
            },
        ),
        migrations.CreateModel(
            name='Week24',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 24', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week24',
            },
        ),
        migrations.CreateModel(
            name='Week23',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 23', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week23',
            },
        ),
        migrations.CreateModel(
            name='Week22',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 22', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week22',
            },
        ),
        migrations.CreateModel(
            name='Week21',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 21', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week21',
            },
        ),
        migrations.CreateModel(
            name='Week20',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 20', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week20',
            },
        ),
        migrations.CreateModel(
            name='Week2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 2', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week2',
            },
        ),
        migrations.CreateModel(
            name='Week19',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 19', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week19',
            },
        ),
        migrations.CreateModel(
            name='Week18',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 18', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week18',
            },
        ),
        migrations.CreateModel(
            name='Week17',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 17', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week17',
            },
        ),
        migrations.CreateModel(
            name='Week16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 16', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week16',
            },
        ),
        migrations.CreateModel(
            name='Week15',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 15', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week15',
            },
        ),
        migrations.CreateModel(
            name='Week14',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 14', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week14',
            },
        ),
        migrations.CreateModel(
            name='Week13',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 13', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week13',
            },
        ),
        migrations.CreateModel(
            name='Week12',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 12', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week12',
            },
        ),
        migrations.CreateModel(
            name='Week11',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 11', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week11',
            },
        ),
        migrations.CreateModel(
            name='Week10',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 10', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week10',
            },
        ),
        migrations.CreateModel(
            name='Week1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('WeekName', models.CharField(default='Wiki 1', max_length=500)),
                ('Time', models.CharField(blank=True, default='BREAKFAST', max_length=100, null=True)),
                ('Description', models.TextField(blank=True, max_length=1000, null=True)),
                ('FoodImage', models.ImageField(blank=True, null=True, upload_to='media/WeekImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'Week1',
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(blank=True, max_length=256, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='token', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='TaarifaZaWatoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KULIA MARA KWA MARA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaWatoto',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaUzitoZaidi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KUCHOKA MARA KWA MARA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaUzitoZaidi',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaUjauzito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='UJAZO WA MTOTO', max_length=500)),
                ('Description', models.TextField(blank=True, default='Mchanga kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaUjauzito',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaKisukari',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='MGONGO KUUMA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaKisukari',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaHiv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='KUTOKWA NA VIPELE MWILINI', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaHiv',
            },
        ),
        migrations.CreateModel(
            name='TaarifaZaFamilia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='Description here', max_length=500)),
                ('Description', models.TextField(blank=True, default='Wiki ya kwanza kabisa', max_length=1000, null=True)),
                ('InformationImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'TaarifaZaFamilia',
            },
        ),
        migrations.CreateModel(
            name='JeWajua',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='WANGA', max_length=500)),
                ('Description', models.TextField(blank=True, default='Inasaidia kuimarisha misuli ya tumbo', max_length=1000, null=True)),
                ('ItemImage', models.ImageField(blank=True, null=True, upload_to='media/LisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
                ('Week', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.weeks')),
            ],
            options={
                'verbose_name_plural': 'JeWajua',
            },
        ),
        migrations.CreateModel(
            name='DayTwo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day two', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayTwo',
            },
        ),
        migrations.CreateModel(
            name='DayThree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day three', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayThree',
            },
        ),
        migrations.CreateModel(
            name='DaySix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day six', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DaySix',
            },
        ),
        migrations.CreateModel(
            name='DaySeven',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day seven', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DaySeven',
            },
        ),
        migrations.CreateModel(
            name='DayOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day one', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayOne',
            },
        ),
        migrations.CreateModel(
            name='DayFour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day four', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayFour',
            },
        ),
        migrations.CreateModel(
            name='DayFive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DayName', models.CharField(default='Day five', max_length=500)),
                ('Time', models.CharField(blank=True, choices=[('ASUBUHI', 'ASUBUHI'), ('MCHANA', 'MCHANA'), ('JIONI', 'JIONI'), ('USIKU', 'USIKU')], max_length=100, null=True)),
                ('DayDescription', models.TextField(blank=True, max_length=1000, null=True)),
                ('DayImage', models.ImageField(blank=True, null=True, upload_to='media/ElimuYaLisheImages/')),
                ('Created', models.DateTimeField(auto_now_add=True)),
                ('Updated', models.DateTimeField(auto_now=True)),
                ('Category', models.ForeignKey(max_length=500, on_delete=django.db.models.deletion.CASCADE, to='LisheApp.lishe')),
            ],
            options={
                'verbose_name_plural': 'DayFive',
            },
        ),
    ]
